---
title: "Cor/Raça e Funções"
output: 
  html_document:
    theme: bootstrap
---
<!-- <style type="text/css"> -->
<!-- .main-container { -->
<!--   max-width: 90%; -->
<!--   margin-left: auto; -->
<!--   margin-right: auto; -->
<!-- } -->
<!-- </style> -->
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
```

```{r pkg-load}
library(dplyr)
library(leaflet)
library(DT)
library(ggplot2)
library(plotly)
library(crosstalk)
library(readxl)
library(RColorBrewer)
```

```{r data-load}

#Por órgão 

dados <- readRDS("../data/Tab.rds") 

sd_total <- SharedData$new(dados)

```

```{r filtro_orgao}
filtro_Orgao <- filter_select("Orgao", 
                              "Selecione um Órgão", 
                              sd_total, 
                              ~Orgão,
                              multiple = FALSE
                              )

filtro_funcao <- filter_select("Funcao", 
                                 "Selecione um Cargo-Função", 
                                 sd_total, 
                                 ~`Cargo-Função`, multiple = FALSE
                                 #inline = TRUE,
                                 #columns = 1
                                 )


# l <- list(
#   font = list(
#     family = "sans-serif",
#     size = 12,
#     color = "#333"),
#   bgcolor = "white",
#   bordercolor = "white",
#   x = 0, y = 1,
#   orientation = "h",
#   borderwidth = 1,
#   title=list(text='<b> Cargos e Funções </b>'))

bars_fem <- plot_ly(sd_total)  |> 
  add_bars(width=0.8,
           x =  ~Etnia,
           y =  ~Fem,
           #color = ~`Cargo-Função`,#I("#89CFF0"),
           colors =  brewer.pal(n = 10, name = "PuBu"),
           text = ~`Cargo-Função`,
           #name = ~`Cargo-Função`,
           opacity=1,
           hovertemplate = paste('%{x} <br> Sexo Feminino: %{y}<extra></extra><br> %{text}')
  ) |> layout(
         xaxis = list(title = "Feminino"),
         yaxis = list(title = "")) |> 
  layout(barmode = "stack") #|> hide_legend()

bars_mas <- plot_ly(sd_total)  |> 
  add_bars(width=0.8,
           x =  ~Etnia,
           y =  ~Mas,
           #color = ~`Cargo-Função`,#I("#89CFF0"),
           colors =  brewer.pal(n = 10, name = "PuBu"),
           text = ~`Cargo-Função`,
           #name = ~`Cargo-Função`,
           opacity=1,
           hovertemplate = paste('%{x} <br> Sexo Masculino: %{y}<extra></extra><br> %{text}')
  ) |> layout(
         xaxis = list(title = "Masculino"),
         yaxis = list(title = "")) |> 
  layout(barmode = "stack") #|> hide_legend()

#fig <- subplot(bars_fem, bars_mas)  |>  
  # layout(title = 'Poder Executivo Federal')


# table

dt <- sd_total |> 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c("Fem", "Mas")
        )
      ),
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    )
  )

```



```{r dados_gerais}

dados_geral <- dados |> 
  dplyr::group_by(
    Etnia, `Cargo-Função`) |> 
  dplyr::summarise(
    Fem = sum(Fem, na.rm = TRUE),
    Mas = sum(Mas, na.rm = TRUE), 
    Total = sum(Total, na.rm = TRUE)
  ) |> 
  dplyr::ungroup() |> 
   group_by(`Cargo-Função`) |> 
  mutate(
    `% Cargo-Função/Etnia` = scales::percent(Total/sum(Total, na.rm = TRUE))
  ) 

sd_Etnia <- SharedData$new(dados_geral)

```


```{r grafico_barra_empilhado}
funcao2 <- filter_select("Funcao2", 
                                 "Selecione um Cargo-Função", 
                                 sd_Etnia, 
                                 ~`Cargo-Função`, multiple = FALSE
                                 #inline = TRUE,
                                 #columns = 1
                                 )

bars_empilhado <- plot_ly(sd_Etnia)  |> 
  add_bars(width=0.8,
           x =  ~Etnia,
           y =  ~Fem,
           #color = ~`Cargo-Função`,#I("#89CFF0"),
           colors =  brewer.pal(n = 10, name = "PuBu"),
           #text = ~`Cargo-Função`,
           name = "Fem",
           opacity=1,
           hovertemplate = paste('%{x}<br>%{y}')
  ) |> layout(
         xaxis = list(title = "Feminino"),
         yaxis = list(title = "")) |> 
  layout(barmode = "stack") |> 
  add_bars(width=0.8,
           x =  ~Etnia,
           y =  ~Mas,
           #color = ~`Cargo-Função`,#I("#89CFF0"),
           colors =  brewer.pal(n = 10, name = "PuBu"),
           #text = ~`Cargo-Função`,
           name = "Mas",
           opacity=1,
           hovertemplate = paste('%{x}<br>%{y}')
  ) |> layout(
         xaxis = list(title = "Cor/Raça - Etnias"),
         yaxis = list(title = "")) |> 
  layout(barmode = "stack") #|> hide_legend() 

# bars_mas2 <- plot_ly(sd_Etnia)  |> 
#   add_bars(width=0.8,
#            x =  ~Etnia,
#            y =  ~Mas,
#            #color = ~`Cargo-Função`,#I("#89CFF0"),
#            colors =  brewer.pal(n = 10, name = "PuBu"),
#            text = ~`Cargo-Função`,
#            #name = ~`Cargo-Função`,
#            opacity=1,
#            hovertemplate = paste('%{x} <br> Sexo Masculino: %{y}<extra></extra><br> %{text}')
#   ) |> layout(
#          xaxis = list(title = "Masculino"),
#          yaxis = list(title = "")) |> 
#   layout(barmode = "stack") #|> hide_legend()

#fig <- subplot(bars_fem, bars_mas)  |>  
  # layout(title = 'Poder Executivo Federal')


# table

dt2 <- sd_Etnia |> 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c("Fem", "Mas")
        )
      ),
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    )
  )

```

```{r}
# dados_serie <- readRDS("../data/serie.rds") 
# 
# sd_serie <- SharedData$new(dados_serie, group = "dados_serie")  
# filtro_funcao3 <- filter_select("Funcao3", 
#                                "Selecione um Cargo-Função", 
#                                sd_serie, 
#                                ~Agrupamento2,
#                                multiple = FALSE)
#  
# ax <- list(
#   title = "",
#   zeroline = FALSE,
#   showline = FALSE,
#   showticklabels = FALSE
# )
# 
# 
# fig1 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~BRANCA, name = ~Agrupamento2)%>%
#   layout(legend=list(title=list(text='Cor/Raça-Etnia')), xaxis = ax, yaxis = list(range = c(0.0,.8), title = ''))
# 
# 
# fig2 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~PARDA, name = ~Agrupamento2)%>%
#   layout(legend=list(title=list(text='Cor/Raça-Etnia')), xaxis = ax, yaxis = list(range = c(0.0,0.8),title = '', showticklabels = TRUE))
# 
# 
# fig3 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~PRETA, name = ~Agrupamento2)%>%
#   layout(legend=list(title=list(text='Cor/Raça-Etnia')), xaxis = ax, yaxis = list(range = c(0.0,0.3), title = 'Decreto'))
# 
# 
# fig4 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~AMARELA, name = ~Agrupamento2)%>%
#   layout(legend=list(title=list(text='Cor/Raça-Etnia')), xaxis = ax, yaxis = list(range = c(0.0,0.3),title = '', showticklabels = TRUE))
# 
# 
# fig5 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~INDIGENA, name = ~Agrupamento2)%>%
#   layout(legend=list(title=list(text='Cor/Raça-Etnia')),  yaxis = list(range = c(0.0,0.1),title = '', showticklabels = TRUE), xaxis = list(title = 'Data'))
# 
# 
# fig6 <- plot_ly(sd_serie, type = 'scatter', mode = 'lines', fill = 'tonexty')%>%
#   add_trace(x = ~Data, y = ~`NAO INFORMADO`, name = ~Agrupamento2)%>%
#   layout( legend=list(title=list(text='Cor/Raça-Etnia')), yaxis = list(range = c(0.0,0.1) ,showticklabels = TRUE, title =''),  xaxis = list(title = 'Data'))
# 
# 
# fig <- subplot(fig1, fig2, fig3, fig4, fig5, fig6,
#                nrows = 3, titleY = TRUE, titleX = TRUE) %>% layout(
#                  xaxis = list(zerolinecolor = '#ffff',
#                               zerolinewidth = 2,
#                               gridcolor = 'ffff'),
#                  yaxis = list(zerolinecolor = '#ffff',
#                               zerolinewidth = 2,
#                               gridcolor = 'ffff'),
#                  plot_bgcolor='#e5ecf6')
# annotations = list(
#   list(
#     x = 0.225,
#     y = 1.0,
#     font = list(size = 10),
#     text = "Branca",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   ),
#   list(
#     x = 0.775,
#     y = 1,
#     font = list(size = 10),
#     text = "Parda",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   ),
#   list(
#     x = 0.225,
#     y = 0.64,
#     font = list(size = 10),
#     text = "Preta",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   ),
#   list(
#     x = 0.775,
#     y = 0.64,
#     font = list(size = 10),
#     text = "Amarela",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   ),
#   list(
#     x = 0.225,
#     y = 0.315,
#     font = list(size = 10),
#     text = "Indígena",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   ),
#   list(
#     x = 0.775,
#     y = 0.315,
#     font = list(size = 10),
#     text = "Não Informado",
#     xref = "paper",
#     yref = "paper",
#     xanchor = "center",
#     yanchor = "bottom",
#     showarrow = FALSE
#   )
# )
# 
# fig <- fig %>%layout(annotations = annotations, width = 1000)|> hide_legend()
# options(warn = -1)
# 
# 

```
  


```{r pizza}


data_funcao <- dados |> select(`Natureza Jurídica`,
                               `Orgão Superior`,
                               Orgão, Etnia, `Cargo-Função`, Total) |> 
  tidyr::pivot_wider(names_from = `Cargo-Função`, values_from = Total) |> 
  filter(Orgão != "Agencia Brasileira De Inteligencia")

sd_pizza <- SharedData$new(data_funcao)

filtro_Orgao <- filter_select("Orgao", 
                              "Selecione um Órgão", 
                              sd_pizza, 
                              ~Orgão,
                              multiple = FALSE
                              )

pier_Nivel1a12 <- plot_ly() |>  
  add_pie(
    data = sd_pizza,
    labels = ~Etnia,
    values = ~`nível 1 a 12`,
    name = "Nível 1 a 12",
    domain = list(x = c(0, 0.4), y = c(0, 1))
  )   

pier_Nivel13a17 <- plot_ly() |>  
  add_pie(
    data = sd_pizza,
    labels = ~Etnia,
    values = ~`nível 13 a 17`,
    name = "Nível 13 a 17",
    domain = list(x = c(0.6, 1), y = c(0, 1))
  )   
   





s1 <- subplot(pier_Nivel1a12, pier_Nivel13a17)|>  
  layout(annotations = list( 
    list(x = 0.10 , y = 1.1, text = "Nível 1 a 12", showarrow = F, xref='paper', yref='paper'), 
    list(x = 0.85 , y = 1.1, text = "Nível 13 a 17", showarrow = F, xref='paper', yref='paper')) 
  ) 

# pier <- pier |>  layout(title = "% Pessoas Negras em Cargos Comissionados", showlegend = F,
#          xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
#          yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig <- s1 |>  
  layout(title = "% Pessoas Negras em Cargos Comissionados",
         plot_bgcolor='#e5ecf6', 
         xaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'), 
         yaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'),
         showlegend=TRUE,showlegend2=TRUE, 
         margin = 0.01) 




# table

dt2 <- sd_pizza |> 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      # columnDefs = list(
      #   list(
      #     visible = FALSE,
      #     targets = c("Fem", "Mas")
      #   )
      # ),
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    )
  )
```


## Dados gerais

% Pessoas Negras em Cargos Comissionados segundo critério estabelecido pelo Decreto nº  11.443, de 21 de março de 2023


### Março de 2023

Nível 1 a 12

```{r pizza_nivel_1a12, fig.height=12, fig.width=12}
bscols(filtro_Orgao, fig,dt2,   widths = c(12, 12, 12))
```





```{r}
# # Cargo funçao por sexo
# bscols(
#   funcao2,
#   bars_empilhado,
#   #bars_mas2,
#   dt2, 
#   widths = c(12, 12, 12))
```



```{r}
# bscols(
#   filtro_funcao3,
#   fig,
#   widths = c(12, 12))
  
``` 



```{r}
# create final output ----
# bscols(
#   filtro_Orgao,
#   filtro_funcao,
#   bars_fem,
#   bars_mas,
#   dt, 
#   widths = c(6, 6, 12, 12, 12))
```



```{js echo=FALSE, message=FALSE, warning=FALSE}
function filter_default() {
    document.getElementById("Orgao").getElementsByClassName("selectized")
[0].selectize.setValue("", false);
    document.getElementById("Funcao").getElementsByClassName("selectized")
[0].selectize.setValue("nível 1 a 12", false);
<!--     document.getElementById("Funcao2").getElementsByClassName("selectized") -->
<!-- [0].selectize.setValue("Nível 1 a 12", false); -->
<!--     document.getElementById("Funcao3").getElementsByClassName("selectized") -->
<!-- [0].selectize.setValue("FCPE &amp; FEX", false); -->
 }
window.onload = filter_default;
```