---
output: 
  html_document:
    theme: bootstrap
---

```{=html}
<style type="text/css">

.main-container {

  max-width: 90%;

  margin-left: auto;

  margin-right: auto;

}

strong {
    font-weight: 700;
    color: #0c326f;
    
}

label {
    display: inline-block;
    max-width: 100%;
    margin-bottom: 5px;
    font-weight: 700;
    color: #0c326f;
}

element.style {
    width: 242.639px;
    color: #0c326f;
}

</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
```

```{r pkg-load}
library(DT)
library(plotly)
library(crosstalk)
library(readxl)
library(RColorBrewer)
library(tidyverse)
library(reactablefmtr)
library(sysfonts)
library(showtext)
library(htmltools)
library(htmlwidgets)
```

```{r data-load}

#Por órgão 

dados <- readRDS("../data/Tab.rds") |> filter(Órgão != "Agencia Brasileira De Inteligencia") |> dplyr::rename(`Raça/Cor` = etnia, 
                                 `%` = `% Cargo-Função/Etnia`)

sd_total <- SharedData$new(dados, group = "funcao")

```

```{r filtro_orgao}
filtro_Orgao <- filter_select("Orgao", 
                              "Selecione um Órgão", 
                              sd_total, 
                              ~Órgão,
                              allLevels = TRUE,
                              multiple = FALSE
                              )

filtro_funcao <- filter_select("Funcao", 
                                 "Selecione um Cargo-Função", 
                                 sd_total, 
                                 ~`Cargo-Função`, multiple = FALSE
                                 #inline = TRUE,
                                 #columns = 1
                                 )


```

```{r pizza}
data_funcao <- dados |> select(`Órgão Superior`,
                               Órgão, `Raça/Cor`, 
                               `Cargo-Função`, Fem, Mas, Total) |> 
  tidyr::pivot_wider(names_from = `Cargo-Função`, values_from = Total) |> 
  filter(Órgão != "Agencia Brasileira De Inteligencia")


sd_pizza <- SharedData$new(data_funcao, group = "funcao")

filtro_Orgao_pizza <- filter_select("Orgao_PIZZA", 
                              "Selecione um Órgão", 
                              sd_pizza, 
                              allLevels = TRUE,
                              ~Órgão,
                              multiple = FALSE
                              )

pier_Nivel1a12 <- plot_ly() |>  
  add_pie(
    data = sd_pizza,
    labels = ~`Raça/Cor`,
    values = ~`Nível 1 a 12`,
    name = "Nível 1 a 12"
    #domain = list(x = c(0, 0.4), y = c(0, 1))
  )   

pier_Nivel13a17 <- plot_ly() |>  
  add_pie(
    data = sd_pizza,
    labels = ~`Raça/Cor`,
    values = ~`Nível 13 a 17`,
    name = "Nível 13 a 17"
    #domain = list(x = c(0.6, 1), y = c(0, 1))
  )   
   

figpier_Nivel1a12 <- pier_Nivel1a12 |>  
  layout(title = "Nível 1 a 12",
         plot_bgcolor='#e5ecf6', 
         xaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'), 
         yaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'),
         showlegend=TRUE,showlegend2=TRUE, 
         margin = 0.01) 

figpier_Nivel13a17 <- pier_Nivel13a17 |>  
  layout(title = "Nível 13 a 17",
         plot_bgcolor='#e5ecf6', 
         xaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'), 
         yaxis = list( 
           zerolinecolor = '#ffff', 
           zerolinewidth = 2, 
           gridcolor = 'ffff'),
         showlegend=TRUE,showlegend2=TRUE, 
         margin = 0.01) 


# table

# Definir as configurações da tabela, incluindo o idioma em Português Brasil


# Criar a tabela usando datatable com as configurações personalizadas
```

```{r}

configuracao <- list(
  language = list(
    infoFiltered = "(filtrado num total de _MAX_ registros)",
    info = "Exibindo _START_ até _END_ de _TOTAL_ registros",
    lengthMenu = "Mostrar _MENU_ registros por página",
    search = "Pesquisar:",
    paginate = list(
      first = "Primeiro",
      last = "Último",
      `next` = "Próximo",
      previous = "Anterior"),
    aria = list(
      sortAscending = ": ativar para classificar coluna em ordem crescente",
      sortDescending = ": ativar para classificar coluna em ordem decrescente"
    )
  ),
  dom = 'Bfrtip',
  buttons = c('csv', 'excel', 'pdf', 'print')
  
)
```

```{r}
dt2 <- sd_total |> 
  DT::datatable(#filter = "top",
                #style = "bootstrap",
                class = "compact",
                width = "100%",
                extensions = 'Buttons',
                options = configuracao
                )
    
```



```{r Rectable_1a12 }
# AGOSTO

# data <- readRDS("data/data_1a12.rds")
# subdata <-  readRDS("data/subdata1a12.rds")

# Rectable 1a 12 ----------------------------------------------------------

#color palette for difficulty scale
#text_color="#555555",
#pal_strive<-c('#50C4AA', '#B6C95C', '#FACB3E', '#FC800F', '#FF4759')

# Nivel 1 a 12 ------------------------------------------------------------

#Create Reactable
# table<-reactable(
#   data,
#   theme =  default(),
#   defaultColDef = colDef(vAlign="center", align="center", headerVAlign="center"),
#   columns = list(
#     `Órgão Superior` = colDef(name="Órgão Superior", 
#                               align="left", vAlign="center", width=220,
#                               # resizable = TRUE,sortable = TRUE,
#                               # filterable = TRUE,
#                               cell = function(value) {
#                                 tagList(
#                                   div(style = "display: inline-block;vertical-align:middle;width:50px"),
#                                   div(style = "display: inline-block;vertical-align:middle;", value)
#                                 )
#                               }
#     ),
#     Órgão = colDef(name="Órgão", maxWidth=130, align="left"),
#     rank = colDef(name="", style=list(fontSize=13), maxWidth=50, align="right"),
#     Total_serv_1a12 = colDef(name="Nº de Cargos/Funções", minWidth=50),
#     `% Nível 1 a 12` =colDef(name="%", minWidth=120, 
#                              cell=data_bars(data, 
#                                             bar_height=8,
#                                             text_size=11,
#                                             text_color="rgb(51, 51, 51)",
#                                             text_position = "outside-end", 
#                                             background = "transparent", 
#                                             round_edges = TRUE, 
#                                             fill_color=c("#FFBC51",'#FF3A3A'), 
#                                             fill_gradient = TRUE)),
#     tendencia_1a12 = colDef(name="Tendência % Últimos 5 meses",  maxWidth=120,
#                             footer="% Últimos 5 meses",
#                             cell=react_sparkline(data, labels=c("first","last"), 
#                                                  tooltip_size = "1.1em",
#                                                  tooltip_type=1,
#                                                  line_color = "rgb(51, 51, 51)")
#     )
#   ),
#   #Sub-Table 
#   details = function(index){
#     new = subdata[subdata$`Órgão Superior` == data$`Órgão Superior`[index],]
#     reactable(data=new,
#               defaultColDef = colDef(vAlign="center", align="center", headerVAlign="center"),
#               theme =  default(),
#               columns = list(
#                 `Órgão Superior`=colDef(show=FALSE),
#                 rank = colDef(name="", width=295),
#                 Órgão = colDef(name="", maxWidth=130, align="left", footer="", footerStyle=list(color='black')), #
#                 rank = colDef(name="", style=list(fontSize=13), maxWidth=50, align="right"),
#                 `Nível 1 a 12`=colDef(name="Nº de Pessoas Negras", minWidth=50),
#                 Total_serv_1a12 = colDef(name="Nº de Cargos/Funções", minWidth=50),
#                 `% Nível 1 a 12` = colDef(name="", minWidth=120, 
#                                           cell=data_bars(new, 
#                                                          bar_height=8,
#                                                          text_size=11,
#                                                          text_color="rgb(51, 51, 51)",
#                                                          text_position = "outside-end", 
#                                                          background = "transparent", 
#                                                          round_edges = TRUE, 
#                                                          fill_color=c("#FFBC51",'#FF3A3A'), 
#                                                          fill_gradient = TRUE)),
#                 # difficulty = colDef(name="", align="center", maxWidth=120, 
#                 #                     cell=color_tiles(new, bias= 0.4, colors=pal_strive)),
#                 tendencia_1a12 = colDef(name="",  maxWidth=120,
#                                         cell=react_sparkline(new, labels=c("first","last"), 
#                                                              line_color = "rgb(51, 51, 51)")
#                 )
#               )
#     )
#   }
# )%>%
#   google_font(font_family="Roboto", font_weight = 300)
# 
# #use html widgest to prepend an dappend header and footer
# html_object_1a12<-table|>
#   prependContent(
#     tagList(
#       div(style = "vertical-align:middle;text-align:center;background-color:#1351B4;color:white;padding-top:25px;padding-bottom:4px;font-size:24px;",
#           "Percentual de Pessoas Negras (Pretas/Pardas) em Cargos Comissionados de Níveis de 1 a 12"),
#       div(style = "vertical-align:middle;text-align:center;background-color:#1351B4;color:#BBBBBB;padding-top:5px;padding-bottom:20px;font-size:14px;",
#           "Decreto nº 11.443/2023 que reserva às pessoas negras (pretas e pardas) percentual mínimo de 30% na ocupação em Cargos Comissionados Executivos (CCE) e Funções Comissionadas Executivas (FCE)")
#     )
#   )|>
#   appendContent(
#     p("Fonte: Painel Estatístico de Pessoal",
#       style = paste0(
#         "font-family:","Roboto; sans;",
#         "font-size: 12px;" ,
#         "text-align:right"))
#   )

#saveWidget(html_object, "nivel1a12.html", selfcontained = TRUE)

```

```{r Rectable_13a17}

# data <- readRDS("data/data_13a17.rds")
# subdata <-  readRDS("data/subdata_13a17.rds")

# Rectable 13 a 17 ----------------------------------------------------------

#color palette for difficulty scale
#text_color="#555555",
#pal_strive<-c('#50C4AA', '#B6C95C', '#FACB3E', '#FC800F', '#FF4759')

# Nivel 13 a 17 ------------------------------------------------------------

#Create Reactable
# table<-reactable(
#   data,
#   theme =  default(),
#   
#   defaultColDef = colDef(vAlign="center", align="center", headerVAlign="center"),
#   columns = list(
#     `Órgão Superior` = colDef(name="Órgão Superior", 
#                               align="left", vAlign="center", width=220,
#                               # resizable = TRUE,sortable = TRUE,
#                               # filterable = TRUE,
#                               cell = function(value) {
#                                 tagList(
#                                   div(style = "display: inline-block;vertical-align:middle;width:50px"),
#                                   div(style = "display: inline-block;vertical-align:middle;", value)
#                                 )
#                               }
#     ),
#     Órgão = colDef(name="Órgão", maxWidth=130, align="left"),
#     rank = colDef(name="", style=list(fontSize=13), maxWidth=50, align="right"),
#     Total_serv_13a17 = colDef(name="Nº de Cargos/Funções", minWidth=50),
#     `% Nível 13 a 17` =colDef(name="%", minWidth=120, 
#                               cell=data_bars(data, 
#                                              bar_height=8,
#                                              text_size=11,
#                                              text_color="rgb(51, 51, 51)",
#                                              text_position = "outside-end", 
#                                              background = "transparent", 
#                                              round_edges = TRUE, 
#                                              fill_color=c("#FFBC51",'#FF3A3A'), 
#                                              fill_gradient = TRUE)),
#     tendencia_13a17 = colDef(name="Tendência %",  maxWidth=120,
#                              footer="% Últimos 5 meses",
#                              cell=react_sparkline(data, labels=c("first","last"), 
#                                                   tooltip_size = "1.1em",
#                                                   tooltip_type=1,
#                                                   line_color = "rgb(51, 51, 51)")
#     )
#   ),
#   #Sub-Table 
#   details = function(index){
#     new = subdata[subdata$`Órgão Superior` == data$`Órgão Superior`[index],]
#     reactable(data=new,
#               defaultColDef = colDef(vAlign="center", align="center", headerVAlign="center"),
#               theme =  default(),
#               columns = list(
#                 `Órgão Superior`=colDef(show=FALSE),
#                 rank = colDef(name="", width=295),
#                 Órgão = colDef(name="", maxWidth=130, align="left", footer="", footerStyle=list(color='black')), #
#                 rank = colDef(name="", style=list(fontSize=13), maxWidth=50, align="right"),
#                 `Nível 13 a 17`= colDef(name="Nº de Pessoas Negras", minWidth=50),
#                 Total_serv_13a17 = colDef(name="Nº de Cargos/Funções", minWidth=50),
#                 `% Nível 13 a 17` = colDef(name="", minWidth=120, 
#                                            cell=data_bars(new, 
#                                                           bar_height=8,
#                                                           text_size=11,
#                                                           text_color="rgb(51, 51, 51)",
#                                                           text_position = "outside-end", 
#                                                           background = "transparent", 
#                                                           round_edges = TRUE, 
#                                                           fill_color=c("#FFBC51",'#FF3A3A'), 
#                                                           fill_gradient = TRUE)),
#                 tendencia_13a17 = colDef(name="",  maxWidth=120,
#                                          cell=react_sparkline(new, labels=c("first","last"), 
#                                                               line_color = "rgb(51, 51, 51)")
#                 )
#               )
#     )
#   }
# )%>%
#   google_font(font_family="Roboto", font_weight = 300)
# 
# 
# #use html widgest to prepend an dappend header and footer
# html_object_13a17<-table|>
#   prependContent(
#     tagList(
#       div(style = "vertical-align:middle;text-align:center;background-color:#1351B4;color:white;padding-top:25px;padding-bottom:4px;font-size:24px;",
#           "Percentual de Pessoas Negras (Pretas/Pardas) em Cargos Comissionados de Níveis de 13 a 17"),
#       div(style = "vertical-align:middle;text-align:center;background-color:#1351B4;color:#BBBBBB;padding-top:5px;padding-bottom:20px;font-size:14px;",
#           "Decreto nº 11.443/2023 que reserva às pessoas negras (pretas e pardas) percentual mínimo de 30% na ocupação em Cargos Comissionados Executivos (CCE) e Funções Comissionadas Executivas (FCE)")
#     )
#   )|>
#   appendContent(
#     p("Fonte: Painel Estatístico de Pessoal",
#       style = paste0(
#         "font-family:","Roboto; sans;",
#         "font-size: 12px;" ,
#         "text-align:right"))
#   )


#saveWidget(html_object, "nivel13a17.html", selfcontained = TRUE)
```

### **Percentual de Pessoas Negras (Pretas/Pardas) em Cargos Comissionados**

-   *`Posição Julho de 2023`*

```{r pizza_nivel_1a12, fig.height=12, fig.width=12}
bscols(filtro_Orgao_pizza, widths = 6)
bscols( 
       figpier_Nivel1a12,
       figpier_Nivel13a17,
       widths = c( 6, 6), 
       device = "sm")
```


```{r tabela1a12}
bscols(#html_object_1a12,
  dt2,
       widths = 12,
       device = "sm")
```


```{r chuck pizza_nivel_1a12, fig.height=12, fig.width=12}
# html_object <- bscols(
#        # ranking_1_a_12,
#        # ranking_13_a_17,
#        filtro_Orgao_pizza,
#        figpier_Nivel1a12,
#        figpier_Nivel13a17,
#        widths = c(
#          #6,6,
#          12, 6,6),
#        device = "sm")
# 
# bscols(filtro_Orgao_pizza, widths = 6)
# 
# htmlwidgets::saveWidget(html_object, "pag_inicial.html", selfcontained = TRUE)

```
<!-- Nível correspondente de Cargo Comissionado Executivo -- CCE ou de Função Comissionada Executiva - FCE - Anexo III do Decreto nº10.829, de 5 de outubro de 2021 -->

<!-- | Nível do cargo em Comissão, da Função de Confiança ou da Função Gratificada  | Nível correspondente de Cargo Comissionado Executivo -- CCE ou de Função Comissionada Executiva - FCE  | -->
<!-- |-------------------------------|-----------------------------------------| -->
<!-- | DAS/FCPE - 3                                                                 | Nível 10 a 12                                                                                          | -->
<!-- | DAS/FCPE - 2                                                                 | Nível 7 a 9                                                                                            | -->
<!-- | DAS/FCPE - 1                                                                 | Nível 5 e 6                                                                                            | -->
<!-- | FG -- 1                                                                      | Nível 3 e 4                                                                                            | -->
<!-- | FG -- 2                                                                      | Nível 2                                                                                                | -->
<!-- | FG - 3                                                                       | Nível 1                                                                                                | -->



```{r tabela13a17}
# bscols(html_object_13a17,
#        widths = 12,
#        device = "sm")
```

<!-- Correspondente de Cargo Comissionado Executivo -- CCE ou de Função Comissionada Executiva - FCE - Anexo III do Decreto nº10.829, de 5 de outubro de 2021 -->

<!-- | Nível do cargo em Comissão, da Função de Confiança ou da Função Gratificada  | Nível correspondente de Cargo Comissionado Executivo -- CCE ou de Função Comissionada Executiva - FCE  | -->
<!-- |-------------------------------|-----------------------------------------| -->
<!-- | DAS/FCPE - 6                                                                 | Nível 17                                                                                               | -->
<!-- | DAS/FCPE - 5                                                                 | Nível 15 a16                                                                                           | -->
<!-- | DAS/FCPE - 4                                                                 | Nível 13 a 14                                                                                          | -->


```{js echo=FALSE, message=FALSE, warning=FALSE}

// Obtém o elemento com ID "Orgao_PIZZA"
const orgaoSelectize = document.getElementById("Orgao_PIZZA").getElementsByClassName("selectized")[0];

// Verifica se o valor selecionado é igual a "all" (ou qualquer outro valor que você queira verificar)
if (orgaoSelectize.value === "(All)" {
  // Atribui um valor vazio ao Selectize e evita a atualização do valor selecionado
  selectize.setValue("", false);
}


$(seletor).DataTable({
      data: dt2, // array com dados
      columns: colunas, // vetor com nome das colunas
      language: {
        url:"js/lib/pt_br.json"
      }
})
```
